const apiBaseUrl = 'http://localhost:8000';
const games = { all: 'Todos os TCGs', magic: 'Magic', pokemon: 'Pokémon', yugioh: 'Yu-Gi-Oh!', onepiece: 'One Piece', fab: 'Flesh and Blood' };
const demoCards = [
  { id: 1, name_en: 'Assassin Creed', game: 'magic', rarity: 'Mítica', edition_id: 'Universes Beyond', image: 'assets/trending-01.jpg' },
  { id: 2, name_en: 'Arcane Vanguard', game: 'pokemon', rarity: 'Rara', edition_id: 'Scarlet & Violet', image: 'assets/trending-02.jpg' },
  { id: 3, name_en: 'Neon Genesis', game: 'yugioh', rarity: 'Ultra rara', edition_id: 'Duelist Nexus', image: 'assets/trending-03.jpg' },
  { id: 4, name_en: 'Warframe Prime', game: 'onepiece', rarity: 'Rara', edition_id: 'The Lost Caverns', image: 'assets/trending-04.jpg' },
  { id: 5, name_en: 'Shadow Protocol', game: 'fab', rarity: 'Especial', edition_id: 'Outsiders', image: 'assets/top-game-01.jpg' }
];
const state = { cards: demoCards, game: 'all', search: '', loggedIn: sessionStorage.getItem('cardvault-user') === 'true' };
const app = document.querySelector('#app');
const toast = document.querySelector('#toast');
const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char]));
const gameLabel = (game) => games[game] || game;
function notify(message, error = false) { toast.textContent = message; toast.className = `toast visible${error ? ' error' : ''}`; setTimeout(() => { toast.className = 'toast'; }, 3200); }
function inputField(label, name, type = 'text', placeholder = '', required = true) { return `<label class="field"><span>${label}</span><input name="${name}" type="${type}" placeholder="${placeholder}" ${required ? 'required' : ''}></label>`; }
function authShell(title, subtitle, form) { return `<main class="auth-page"><a class="brand auth-brand" href="#login"><span class="brand-mark">CV</span><span>Card<span>Vault</span></span></a><section class="auth-panel"><div class="auth-kicker">PORTAL DE COLECIONADORES</div><h1>${title}</h1><p class="auth-subtitle">${subtitle}</p>${form}</section><p class="auth-footer">CardVault · seu acervo, sua história.</p></main>`; }
function renderLogin() { app.innerHTML = authShell('Entre no seu acervo.', 'Acesse suas cartas e mantenha tudo organizado em um só lugar.', `<form id="login-form" class="auth-form">${inputField('E-mail', 'email', 'email', 'voce@email.com')}${inputField('Senha', 'password', 'password', '••••••••')}<div class="form-row"><label class="check"><input type="checkbox"> Lembrar de mim</label><a href="#forgot">Esqueci minha senha</a></div><button class="primary-button full" type="submit">Entrar <span>→</span></button><p class="form-switch">Ainda não tem conta? <a href="#register">Criar cadastro</a></p><p class="demo-hint">Modo demonstração: qualquer e-mail e senha funcionam se a API estiver indisponível.</p></form>`); document.querySelector('#login-form').addEventListener('submit', login); }
function renderRegister() { app.innerHTML = authShell('Comece sua coleção.', 'Crie seu acesso gratuito e catalogue suas cartas com clareza.', `<form id="register-form" class="auth-form">${inputField('Seu nome', 'name', 'text', 'Como podemos chamar você?')}${inputField('E-mail', 'email', 'email', 'voce@email.com')}${inputField('Senha', 'password', 'password', 'Mínimo de 6 caracteres')}<button class="primary-button full" type="submit">Criar minha conta <span>→</span></button><p class="form-switch">Já possui uma conta? <a href="#login">Entrar</a></p></form>`); document.querySelector('#register-form').addEventListener('submit', register); }
function renderForgot() { app.innerHTML = authShell('Recupere seu acesso.', 'Enviaremos um link para o e-mail associado à sua conta.', `<form id="forgot-form" class="auth-form">${inputField('E-mail', 'email', 'email', 'voce@email.com')}<button class="primary-button full" type="submit">Enviar instruções <span>→</span></button><p class="form-switch"><a href="#login">← Voltar para o login</a></p></form>`); document.querySelector('#forgot-form').addEventListener('submit', forgot); }
function renderDashboard() { app.innerHTML = `<div class="site-shell"><header class="site-header"><a class="brand" href="#dashboard"><span class="brand-mark">CV</span><span>Card<span>Vault</span></span></a><nav class="main-nav"><a class="active" href="#dashboard">Visão geral</a><a href="#dashboard">Meu acervo</a></nav><button class="profile-button" id="logout-button"><span class="avatar">NT</span><span class="profile-copy"><strong>Minha conta</strong><small>Sair do portal</small></span><span>⌄</span></button></header><main class="dashboard"><section class="dashboard-hero"><div><p class="eyebrow">SEU PORTAL DE CARTAS</p><h1>Seu acervo.<br><em>Sua história.</em></h1><p>Organize, encontre e cuide de cada carta da sua coleção em um só lugar.</p></div><div class="hero-art"><div class="hero-orbit"></div><img src="assets/banner-image.jpg" alt="Carta em destaque"><span class="hero-badge">5 TCGs<br><small>em um só lugar</small></span></div></section><section class="quick-stats"><div><span class="stat-icon coral">✦</span><p><strong>${state.cards.length}</strong><small>cartas no acervo</small></p></div><div><span class="stat-icon blue">◈</span><p><strong>5</strong><small>TCGs disponíveis</small></p></div><div><span class="stat-icon gold">◇</span><p><strong>${new Set(state.cards.map((card) => card.game)).size}</strong><small>jogos catalogados</small></p></div><div><span class="stat-icon ink">↗</span><p><strong>100%</strong><small>sob seu controle</small></p></div></section><section class="catalog-section"><div class="section-heading"><div><p class="eyebrow">INVENTÁRIO</p><h2>Suas cartas</h2></div><button class="primary-button" id="new-card-button">＋ Nova carta</button></div><div class="toolbar"><label class="search-field"><span>⌕</span><input id="search-input" type="search" placeholder="Buscar por nome ou edição" value="${escapeHtml(state.search)}"></label><div class="filter-tabs" role="tablist">${Object.entries(games).map(([key, label]) => `<button class="filter-tab ${state.game === key ? 'active' : ''}" data-game="${key}" type="button">${label}</button>`).join('')}</div></div><div class="catalog-grid" id="card-grid"></div><p class="empty-state" id="empty-state" hidden>Nenhuma carta encontrada para essa busca.</p></section></main><footer><span>CardVault</span><small>Gerenciador de cartas para colecionadores · © 2026</small></footer></div>`; bindDashboard(); renderCards(); loadCards(); }
function renderCards() { const query = state.search.trim().toLowerCase(); const visible = state.cards.filter((card) => (state.game === 'all' || card.game === state.game) && (!query || `${card.name_en} ${card.name_pt || ''} ${card.edition_id || card.edition || ''}`.toLowerCase().includes(query))); document.querySelector('#card-grid').innerHTML = visible.map((card) => `<article class="card"><div class="card-image"><img src="${escapeHtml(card.image || 'assets/banner-image.jpg')}" alt="${escapeHtml(card.name_en)}"><span class="rarity">${escapeHtml(card.rarity || 'Coleção')}</span></div><div class="card-body"><p class="card-game">${escapeHtml(gameLabel(card.game))}</p><h3>${escapeHtml(card.name_pt || card.name_en)}</h3><span class="card-edition">${escapeHtml(card.edition_id || card.edition || 'Edição não informada')}</span><div class="card-actions"><button data-edit="${card.id}" type="button">Editar</button><button data-delete="${card.id}" type="button">Excluir</button></div></div></article>`).join(''); document.querySelector('#empty-state').hidden = visible.length > 0; document.querySelectorAll('[data-edit]').forEach((button) => button.addEventListener('click', () => openCardModal(Number(button.dataset.edit)))); document.querySelectorAll('[data-delete]').forEach((button) => button.addEventListener('click', () => deleteCard(Number(button.dataset.delete)))); }
function bindDashboard() { document.querySelector('#search-input').addEventListener('input', (event) => { state.search = event.target.value; renderCards(); }); document.querySelectorAll('.filter-tab').forEach((button) => button.addEventListener('click', () => { state.game = button.dataset.game; renderDashboard(); })); document.querySelector('#new-card-button').addEventListener('click', () => openCardModal()); document.querySelector('#logout-button').addEventListener('click', logout); }
async function api(path, options = {}) { const response = await fetch(`${apiBaseUrl}${path}`, { credentials: 'include', ...options }); if (!response.ok) { const error = new Error((await response.json().catch(() => ({}))).error || 'Não foi possível concluir a operação.'); error.status = response.status; throw error; } return response.status === 204 ? null : response.json(); }
async function loadCards() { try { const cards = await api('/cards?limit=100'); if (Array.isArray(cards) && cards.length) state.cards = cards; } catch (error) {} renderCards(); }
async function login(event) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); try { await api('/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); } catch (error) { if (error.status) { notify(error.message, true); return; } notify('API indisponível: entrando no modo demonstração.'); } sessionStorage.setItem('cardvault-user', 'true'); state.loggedIn = true; location.hash = '#dashboard'; }
async function register(event) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); try { await api('/register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); notify('Cadastro criado com sucesso.'); } catch (error) { notify(error.message, true); return; } location.hash = '#dashboard'; }
async function forgot(event) { event.preventDefault(); try { await api('/forgot-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); } catch (error) {} notify('Se o e-mail estiver cadastrado, as instruções foram enviadas.'); }
function modalTemplate(card = {}) { return `<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true"><button class="modal-close" id="close-modal" type="button" aria-label="Fechar">×</button><p class="eyebrow">${card.id ? 'EDITAR CARTA' : 'NOVA CARTA'}</p><h2>${card.id ? 'Atualize os detalhes.' : 'Adicione ao seu acervo.'}</h2><form id="card-form" class="card-form"><div class="form-grid">${inputField('Nome da carta', 'name_en', 'text', 'Ex.: Charizard')}${inputField('Nome em português', 'name_pt', 'text', 'Opcional', false)}<label class="field"><span>TCG</span><select name="game" required>${Object.entries(games).filter(([key]) => key !== 'all').map(([key, label]) => `<option value="${key}" ${card.game === key ? 'selected' : ''}>${label}</option>`).join('')}</select></label>${inputField('Edição', 'edition_id', 'text', 'Ex.: Base Set', false)}${inputField('Raridade', 'rarity', 'text', 'Ex.: Rara', false)}${inputField('URL da imagem', 'image_url', 'url', 'https://...', false)}</div><div class="modal-actions"><button class="secondary-button" id="cancel-modal" type="button">Cancelar</button><button class="primary-button" type="submit">Salvar carta <span>→</span></button></div></form></section></div>`; }
function openCardModal(id) { const card = state.cards.find((item) => item.id === id) || {}; document.body.insertAdjacentHTML('beforeend', modalTemplate(card)); const form = document.querySelector('#card-form'); ['name_en', 'name_pt', 'game', 'edition_id', 'rarity', 'image_url'].forEach((name) => { if (card[name] && form.elements[name]) form.elements[name].value = card[name]; }); document.querySelector('#close-modal').addEventListener('click', closeModal); document.querySelector('#cancel-modal').addEventListener('click', closeModal); form.addEventListener('submit', (event) => saveCard(event, id)); }
function closeModal() { document.querySelector('.modal-backdrop')?.remove(); }
async function saveCard(event, id) { event.preventDefault(); const payload = Object.fromEntries(new FormData(event.currentTarget)); try { await api(id ? `/cards/${id}` : '/cards', { method: id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); notify(id ? 'Carta atualizada.' : 'Carta adicionada.'); } catch (error) { state.cards = id ? state.cards.map((card) => card.id === id ? { ...card, ...payload } : card) : [{ ...payload, id: Date.now(), image: payload.image_url }, ...state.cards]; notify('Salvo no modo demonstração.'); } closeModal(); renderDashboard(); }
async function deleteCard(id) { const card = state.cards.find((item) => item.id === id); if (!card || !confirm(`Excluir “${card.name_pt || card.name_en}” do acervo?`)) return; try { await api(`/cards/${id}`, { method: 'DELETE' }); } catch (error) {} state.cards = state.cards.filter((item) => item.id !== id); notify('Carta excluída.'); renderCards(); }
async function logout() { try { await api('/logout', { method: 'POST' }); } catch (error) {} sessionStorage.removeItem('cardvault-user'); state.loggedIn = false; location.hash = '#login'; }
function route() { const routeName = location.hash.replace('#', '') || (state.loggedIn ? 'dashboard' : 'login'); if (routeName === 'dashboard' && !state.loggedIn) return (location.hash = '#login'); if (routeName === 'login') renderLogin(); else if (routeName === 'register') renderRegister(); else if (routeName === 'forgot') renderForgot(); else renderDashboard(); }
function enhanceHero() { const heroArt = document.querySelector('.hero-art'); if (!heroArt || heroArt.dataset.boosterReady) return; heroArt.dataset.boosterReady = 'true'; heroArt.innerHTML = `<div class="booster-pack" aria-label="Abra suas cartas"><div class="card-wrapper" tabindex="0" role="button" aria-label="Virar carta Charizard"><div class="card"><div class="card-front"><div class="card-artwork fire"><img src="assets/banner-image.jpg" alt="Assassino encapuzado"></div><div class="card-info"><h3>Charizard</h3><p class="rarity">Mítica</p></div></div><div class="card-back"></div></div></div><div class="card-wrapper" tabindex="0" role="button" aria-label="Virar carta Blastoise"><div class="card"><div class="card-front"><div class="card-artwork water"><img src="assets/banner-image.jpg" alt="Assassino encapuzado"></div><div class="card-info"><h3>Blastoise</h3><p class="rarity">Rara</p></div></div><div class="card-back"></div></div></div><div class="card-wrapper" tabindex="0" role="button" aria-label="Virar carta Venusaur"><div class="card"><div class="card-front"><div class="card-artwork grass"><img src="assets/banner-image.jpg" alt="Assassino encapuzado"></div><div class="card-info"><h3>Venusaur</h3><p class="rarity">Rara</p></div></div><div class="card-back"></div></div></div></div>`; heroArt.querySelectorAll('.card-wrapper').forEach((wrapper) => { const flip = () => wrapper.classList.toggle('flipped'); wrapper.addEventListener('click', flip); wrapper.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); flip(); } }); }); }
window.addEventListener('hashchange', route); route(); enhanceHero();
